var hierarchy =
[
    [ "WpfHandler.UI.Controls.SelectableGrid.ActiveBorder", "d9/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid_1_1_active_border.html", null ],
    [ "AnimationTimeline", null, [
      [ "WpfHandler.UI.Animations.GridLengthAnimation", "de/d1a/class_wpf_handler_1_1_u_i_1_1_animations_1_1_grid_length_animation.html", null ]
    ] ],
    [ "WpfHandler.Plugins.API", "d2/d9a/class_wpf_handler_1_1_plugins_1_1_a_p_i.html", null ],
    [ "WpfHandler.Dictionaries.API", "dd/dce/class_wpf_handler_1_1_dictionaries_1_1_a_p_i.html", null ],
    [ "Application", null, [
      [ "AutoCollectionExample.App", "d6/db2/class_auto_collection_example_1_1_app.html", null ],
      [ "AutoCollectionExample.App", "d6/db2/class_auto_collection_example_1_1_app.html", null ],
      [ "AutoCollectionExample.App", "d6/db2/class_auto_collection_example_1_1_app.html", null ],
      [ "AutoCollectionExample.App", "d6/db2/class_auto_collection_example_1_1_app.html", null ],
      [ "AutoCollectionExample.App", "d6/db2/class_auto_collection_example_1_1_app.html", null ],
      [ "ExamplePanelDescriptor.App", "de/dac/class_example_panel_descriptor_1_1_app.html", null ],
      [ "ExamplePanelDescriptor.App", "de/dac/class_example_panel_descriptor_1_1_app.html", null ],
      [ "ExamplePanelDescriptor.App", "de/dac/class_example_panel_descriptor_1_1_app.html", null ],
      [ "ExamplePanelDescriptor.App", "de/dac/class_example_panel_descriptor_1_1_app.html", null ],
      [ "ExamplePanelDescriptor.App", "de/dac/class_example_panel_descriptor_1_1_app.html", null ],
      [ "FlatButtonExample.App", "da/d12/class_flat_button_example_1_1_app.html", null ],
      [ "FlatButtonExample.App", "da/d12/class_flat_button_example_1_1_app.html", null ],
      [ "FlatButtonExample.App", "da/d12/class_flat_button_example_1_1_app.html", null ],
      [ "FlatButtonExample.App", "da/d12/class_flat_button_example_1_1_app.html", null ],
      [ "FlatButtonExample.App", "da/d12/class_flat_button_example_1_1_app.html", null ],
      [ "LocalizationSample.App", "dd/de2/class_localization_sample_1_1_app.html", null ],
      [ "LocalizationSample.App", "dd/de2/class_localization_sample_1_1_app.html", null ],
      [ "LocalizationSample.App", "dd/de2/class_localization_sample_1_1_app.html", null ],
      [ "LocalizationSample.App", "dd/de2/class_localization_sample_1_1_app.html", null ],
      [ "LocalizationSample.App", "dd/de2/class_localization_sample_1_1_app.html", null ],
      [ "LogonScreen.App", "d4/d0e/class_logon_screen_1_1_app.html", null ],
      [ "LogonScreen.App", "d4/d0e/class_logon_screen_1_1_app.html", null ],
      [ "LogonScreen.App", "d4/d0e/class_logon_screen_1_1_app.html", null ],
      [ "LogonScreen.App", "d4/d0e/class_logon_screen_1_1_app.html", null ],
      [ "LogonScreen.App", "d4/d0e/class_logon_screen_1_1_app.html", null ],
      [ "MainPluginBasedApp.App", "dc/d6b/class_main_plugin_based_app_1_1_app.html", null ],
      [ "MainPluginBasedApp.App", "dc/d6b/class_main_plugin_based_app_1_1_app.html", null ],
      [ "MainPluginBasedApp.App", "dc/d6b/class_main_plugin_based_app_1_1_app.html", null ],
      [ "MainPluginBasedApp.App", "dc/d6b/class_main_plugin_based_app_1_1_app.html", null ],
      [ "MainPluginBasedApp.App", "dc/d6b/class_main_plugin_based_app_1_1_app.html", null ],
      [ "SwitchPanelExample.App", "dc/df2/class_switch_panel_example_1_1_app.html", null ],
      [ "SwitchPanelExample.App", "dc/df2/class_switch_panel_example_1_1_app.html", null ],
      [ "SwitchPanelExample.App", "dc/df2/class_switch_panel_example_1_1_app.html", null ],
      [ "SwitchPanelExample.App", "dc/df2/class_switch_panel_example_1_1_app.html", null ],
      [ "SwitchPanelExample.App", "dc/df2/class_switch_panel_example_1_1_app.html", null ],
      [ "TextFiledControls.App", "d7/dd1/class_text_filed_controls_1_1_app.html", null ],
      [ "TextFiledControls.App", "d7/dd1/class_text_filed_controls_1_1_app.html", null ],
      [ "TextFiledControls.App", "d7/dd1/class_text_filed_controls_1_1_app.html", null ],
      [ "TextFiledControls.App", "d7/dd1/class_text_filed_controls_1_1_app.html", null ],
      [ "TextFiledControls.App", "d7/dd1/class_text_filed_controls_1_1_app.html", null ],
      [ "TogglesGroupExample.App", "d2/d95/class_toggles_group_example_1_1_app.html", null ],
      [ "TogglesGroupExample.App", "d2/d95/class_toggles_group_example_1_1_app.html", null ],
      [ "TogglesGroupExample.App", "d2/d95/class_toggles_group_example_1_1_app.html", null ],
      [ "TogglesGroupExample.App", "d2/d95/class_toggles_group_example_1_1_app.html", null ],
      [ "TogglesGroupExample.App", "d2/d95/class_toggles_group_example_1_1_app.html", null ]
    ] ],
    [ "ApplicationSettingsBase", null, [
      [ "AutoCollectionExample.Properties.Settings", "d6/d29/class_auto_collection_example_1_1_properties_1_1_settings.html", null ],
      [ "ExamplePanelDescriptor.Properties.Settings", "df/dfb/class_example_panel_descriptor_1_1_properties_1_1_settings.html", null ],
      [ "FlatButtonExample.Properties.Settings", "d8/dba/class_flat_button_example_1_1_properties_1_1_settings.html", null ],
      [ "LocalizationSample.Properties.Settings", "d5/d33/class_localization_sample_1_1_properties_1_1_settings.html", null ],
      [ "LogonScreen.Properties.Settings", "d9/df9/class_logon_screen_1_1_properties_1_1_settings.html", null ],
      [ "MainPluginBasedApp.Properties.Settings", "dc/dac/class_main_plugin_based_app_1_1_properties_1_1_settings.html", null ],
      [ "SwitchPanelExample.Properties.Settings", "df/d35/class_switch_panel_example_1_1_properties_1_1_settings.html", null ],
      [ "TextFiledControls.Properties.Settings", "dd/d41/class_text_filed_controls_1_1_properties_1_1_settings.html", null ],
      [ "TogglesGroupExample.Properties.Settings", "de/da5/class_toggles_group_example_1_1_properties_1_1_settings.html", null ],
      [ "WpfHandler.Properties.Settings", "d7/d4f/class_wpf_handler_1_1_properties_1_1_settings.html", null ]
    ] ],
    [ "Attribute", null, [
      [ "WpfHandler.Dictionaries.LocalizableContentAttribute", "db/dbf/class_wpf_handler_1_1_dictionaries_1_1_localizable_content_attribute.html", [
        [ "WpfHandler.UI.GUIContentAttribute", "d3/dd4/class_wpf_handler_1_1_u_i_1_1_g_u_i_content_attribute.html", [
          [ "WpfHandler.UI.AutoLayout.Configuration.ContentAttribute", "d2/dfc/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_content_attribute.html", null ],
          [ "WpfHandler.UI.AutoLayout.Controls.HeaderAttribute", "d1/d32/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_header_attribute.html", null ],
          [ "WpfHandler.UI.AutoLayout.Controls.LabelAttribute", "d9/d7c/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_label_attribute.html", null ]
        ] ]
      ] ],
      [ "WpfHandler.UI.AutoLayout.Configuration.BeginHorizontalGroupAttribute", "db/d6f/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_begin_horizontal_group_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Configuration.BeginVerticalGroupAttribute", "de/db7/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_begin_vertical_group_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Configuration.CustomControlAttribute", "d1/de8/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_custom_control_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Configuration.EndGroupAttribute", "db/de0/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_end_group_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Configuration.HideInInspectorAttribute", "d4/d91/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_hide_in_inspector_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Configuration.OrderAttribute", "df/d2b/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_order_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.SpaceAttribute", "d8/df1/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_space_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Markups.EnumsCompatibleAttribute", "d0/de7/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_enums_compatible_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Markups.IListCompatibleAttribute", "d3/df0/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_i_list_compatible_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Markups.TypesCompatibleAttribute", "d1/d67/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_types_compatible_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.AutoCollectionPropertiesAttribute", "d7/de8/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_auto_collection_properties_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.FontSizeAttribute", "d8/d18/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_font_size_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.HorizontalAlignAttribute", "da/de4/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_horizontal_align_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.OrientationAttribute", "d4/dae/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_orientation_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.StyleAttribute", "d4/db4/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_style_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.VerticalAlignAttribute", "d6/db9/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_vertical_align_attribute.html", null ],
      [ "WpfHandler.UI.ColorAttribute", "d6/dab/class_wpf_handler_1_1_u_i_1_1_color_attribute.html", [
        [ "WpfHandler.UI.AutoLayout.Options.BackgroundAttribute", "d7/dde/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_background_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.ForegroundAttribute", "dc/df7/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_foreground_attribute.html", null ]
      ] ],
      [ "WpfHandler.UI.Controls.LayoutSizeAttribute", "d7/d51/class_wpf_handler_1_1_u_i_1_1_controls_1_1_layout_size_attribute.html", [
        [ "WpfHandler.UI.AutoLayout.Options.HeightAttribute", "d8/d4b/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_height_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.LabelWidthAttribute", "d2/d77/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_label_width_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.MaxHeightAttribute", "d8/d31/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_max_height_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.MaxWidthAttribute", "de/d94/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_max_width_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.MinHeightAttribute", "d7/dff/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_min_height_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.MinWidthAttribute", "d2/d96/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_min_width_attribute.html", null ],
        [ "WpfHandler.UI.AutoLayout.Options.WidthAttribute", "d6/d44/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_width_attribute.html", null ]
      ] ]
    ] ],
    [ "WpfHandler.UI.Effects.BlurEffect", "d8/d29/class_wpf_handler_1_1_u_i_1_1_effects_1_1_blur_effect.html", null ],
    [ "WpfHandler.Plugins.Constants", "df/d55/class_wpf_handler_1_1_plugins_1_1_constants.html", null ],
    [ "WpfHandler.Dictionaries.DomainContainer", "d1/d18/class_wpf_handler_1_1_dictionaries_1_1_domain_container.html", null ],
    [ "DoubleAnimationBase", null, [
      [ "WpfHandler.UI.Animations.GridLengthAnimation.ExpanderDoubleAnimation", "d8/d40/class_wpf_handler_1_1_u_i_1_1_animations_1_1_grid_length_animation_1_1_expander_double_animation.html", null ]
    ] ],
    [ "WpfHandler.UI.Animations.FloatAnimation", "df/d3e/class_wpf_handler_1_1_u_i_1_1_animations_1_1_float_animation.html", null ],
    [ "FrameworkElement", null, [
      [ "WpfHandler.UI.GUIContent", "db/dd5/class_wpf_handler_1_1_u_i_1_1_g_u_i_content.html", null ]
    ] ],
    [ "IComponentConnector", null, [
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.PluginControl", "db/d3b/class_example_plugin1_1_1_plugin_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.UserControl1", "d3/d75/class_example_plugin1_1_1_user_control1.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.UserControl1", "de/dbb/class_example_plugin2_1_1_user_control1.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "SwitchPanelExample.HandlingPanel", "da/d43/class_switch_panel_example_1_1_handling_panel.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
      [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
      [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
      [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ]
    ] ],
    [ "WpfHandler.UI.AutoLayout.IGUIElement", "da/db2/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_i_g_u_i_element.html", [
      [ "WpfHandler.UI.AutoLayout.Controls.HeaderAttribute", "d1/d32/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_header_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.LabelAttribute", "d9/d7c/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_label_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.SpaceAttribute", "d8/df1/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_space_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.IGUIField", "d3/dac/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_i_g_u_i_field.html", [
        [ "WpfHandler.UI.Controls.CollectionControl", "d5/d8b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_collection_control.html", [
          [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
          [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
          [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
          [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ],
          [ "WpfHandler.UI.Controls.AutoCollection", "d2/d28/class_wpf_handler_1_1_u_i_1_1_controls_1_1_auto_collection.html", null ]
        ] ],
        [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
        [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ]
      ] ],
      [ "WpfHandler.UI.AutoLayout.ILayerAttribute", "d7/d70/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_i_layer_attribute.html", [
        [ "WpfHandler.UI.AutoLayout.ILayerBeginAttribute", "d5/d7b/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_i_layer_begin_attribute.html", [
          [ "WpfHandler.UI.AutoLayout.Configuration.BeginHorizontalGroupAttribute", "db/d6f/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_begin_horizontal_group_attribute.html", null ],
          [ "WpfHandler.UI.AutoLayout.Configuration.BeginVerticalGroupAttribute", "de/db7/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_begin_vertical_group_attribute.html", null ]
        ] ],
        [ "WpfHandler.UI.AutoLayout.ILayerEndAttribute", "df/d01/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_i_layer_end_attribute.html", [
          [ "WpfHandler.UI.AutoLayout.Configuration.EndGroupAttribute", "db/de0/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_configuration_1_1_end_group_attribute.html", null ]
        ] ]
      ] ]
    ] ],
    [ "WpfHandler.UI.AutoLayout.Markups.IGUIElementBindingAttribute", "d4/d32/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_i_g_u_i_element_binding_attribute.html", [
      [ "WpfHandler.UI.AutoLayout.Markups.EnumsCompatibleAttribute", "d0/de7/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_enums_compatible_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Markups.IListCompatibleAttribute", "d3/df0/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_i_list_compatible_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Markups.TypesCompatibleAttribute", "d1/d67/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_markups_1_1_types_compatible_attribute.html", null ]
    ] ],
    [ "WpfHandler.UI.AutoLayout.IGUILayoutOption", "d0/dfe/interface_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_i_g_u_i_layout_option.html", [
      [ "WpfHandler.UI.AutoLayout.Options.AutoCollectionPropertiesAttribute", "d7/de8/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_auto_collection_properties_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.BackgroundAttribute", "d7/dde/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_background_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.FontSizeAttribute", "d8/d18/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_font_size_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.ForegroundAttribute", "dc/df7/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_foreground_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.HeightAttribute", "d8/d4b/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_height_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.HorizontalAlignAttribute", "da/de4/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_horizontal_align_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.LabelWidthAttribute", "d2/d77/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_label_width_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.MaxHeightAttribute", "d8/d31/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_max_height_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.MaxWidthAttribute", "de/d94/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_max_width_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.MinHeightAttribute", "d7/dff/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_min_height_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.MinWidthAttribute", "d2/d96/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_min_width_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.OrientationAttribute", "d4/dae/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_orientation_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.StyleAttribute", "d4/db4/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_style_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.VerticalAlignAttribute", "d6/db9/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_vertical_align_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.WidthAttribute", "d6/d44/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_width_attribute.html", null ]
    ] ],
    [ "WpfHandler.UI.Controls.ILabel", "dd/de2/interface_wpf_handler_1_1_u_i_1_1_controls_1_1_i_label.html", [
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.TextFieldControl", "d2/dda/class_wpf_handler_1_1_u_i_1_1_controls_1_1_text_field_control.html", [
        [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatPasswordBox", "d3/d1f/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_password_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ],
        [ "WpfHandler.UI.Controls.FlatTextBox", "d3/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_text_box.html", null ]
      ] ]
    ] ],
    [ "WpfHandler.UI.Controls.ILayoutOrientation", "d2/d03/interface_wpf_handler_1_1_u_i_1_1_controls_1_1_i_layout_orientation.html", [
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ]
    ] ],
    [ "WpfHandler.UI.Controls.ILayoutSize", "d6/d39/interface_wpf_handler_1_1_u_i_1_1_controls_1_1_i_layout_size.html", [
      [ "WpfHandler.UI.AutoLayout.Controls.SpaceAttribute", "d8/df1/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_space_attribute.html", null ],
      [ "WpfHandler.UI.AutoLayout.Options.FontSizeAttribute", "d8/d18/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_options_1_1_font_size_attribute.html", null ],
      [ "WpfHandler.UI.Controls.LayoutSizeAttribute", "d7/d51/class_wpf_handler_1_1_u_i_1_1_controls_1_1_layout_size_attribute.html", null ]
    ] ],
    [ "IList", null, [
      [ "WpfHandler.UI.Controls.CollectionControl", "d5/d8b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_collection_control.html", null ]
    ] ],
    [ "InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "WpfHandler.Plugins.IPlugin", "d2/d34/interface_wpf_handler_1_1_plugins_1_1_i_plugin.html", [
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ]
    ] ],
    [ "IPlugin", null, [
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ]
    ] ],
    [ "WpfHandler.Plugins.IPluginSettings", "d4/d78/interface_wpf_handler_1_1_plugins_1_1_i_plugin_settings.html", null ],
    [ "WpfHandler.UI.Controls.IToggleControl", "d5/db4/interface_wpf_handler_1_1_u_i_1_1_controls_1_1_i_toggle_control.html", [
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ]
    ] ],
    [ "WpfHandler.UI.AutoLayout.LayoutHandler", "df/d97/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_layout_handler.html", null ],
    [ "WpfHandler.UI.AutoLayout.LayoutLayer", "db/d69/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_layout_layer.html", null ],
    [ "WpfHandler.UI.LocalizationHandler", "d6/de1/class_wpf_handler_1_1_u_i_1_1_localization_handler.html", null ],
    [ "WpfHandler.UI.AutoLayout.UIDescriptor.MembersHandler", "d2/de0/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_u_i_descriptor_1_1_members_handler.html", null ],
    [ "WpfHandler.Plugins.MenuItemMeta", "d7/d16/class_wpf_handler_1_1_plugins_1_1_menu_item_meta.html", null ],
    [ "WpfHandler.UI.Animations.ObjectAnimation", "d6/d01/class_wpf_handler_1_1_u_i_1_1_animations_1_1_object_animation.html", null ],
    [ "LogonScreen.Properties.Resources", "dd/da5/class_logon_screen_1_1_properties_1_1_resources.html", null ],
    [ "WpfHandler.Properties.Resources", "d2/d90/class_wpf_handler_1_1_properties_1_1_resources.html", null ],
    [ "LocalizationSample.Properties.Resources", "d3/da1/class_localization_sample_1_1_properties_1_1_resources.html", null ],
    [ "AutoCollectionExample.Properties.Resources", "d5/dfe/class_auto_collection_example_1_1_properties_1_1_resources.html", null ],
    [ "SwitchPanelExample.Properties.Resources", "dc/d2e/class_switch_panel_example_1_1_properties_1_1_resources.html", null ],
    [ "TogglesGroupExample.Properties.Resources", "d8/d96/class_toggles_group_example_1_1_properties_1_1_resources.html", null ],
    [ "FlatButtonExample.Properties.Resources", "df/de4/class_flat_button_example_1_1_properties_1_1_resources.html", null ],
    [ "ExamplePanelDescriptor.Properties.Resources", "d1/d6c/class_example_panel_descriptor_1_1_properties_1_1_resources.html", null ],
    [ "MainPluginBasedApp.Properties.Resources", "d4/dac/class_main_plugin_based_app_1_1_properties_1_1_resources.html", null ],
    [ "TextFiledControls.Properties.Resources", "dc/d84/class_text_filed_controls_1_1_properties_1_1_resources.html", null ],
    [ "ShaderEffect", null, [
      [ "WpfHandler.UI.Effects.RectBlurEffect", "dd/d01/class_wpf_handler_1_1_u_i_1_1_effects_1_1_rect_blur_effect.html", null ]
    ] ],
    [ "WpfHandler.UI.Animations.ThinknessAnimation", "d7/ded/class_wpf_handler_1_1_u_i_1_1_animations_1_1_thinkness_animation.html", null ],
    [ "WpfHandler.UI.AutoLayout.UIDescriptor", "d1/d72/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_u_i_descriptor.html", [
      [ "AutoCollectionExample.ACExample", "d4/d74/class_auto_collection_example_1_1_a_c_example.html", null ],
      [ "ExamplePanelDescriptor.ExampleDescriptor", "d2/d6f/class_example_panel_descriptor_1_1_example_descriptor.html", null ],
      [ "TextFiledControls.CustomAutolayoutDescriptor", "d2/d1a/class_text_filed_controls_1_1_custom_autolayout_descriptor.html", null ],
      [ "TogglesGroupExample.ExampleDescripotor", "d3/da7/class_toggles_group_example_1_1_example_descripotor.html", null ],
      [ "WpfHandler.UI.AutoLayout.FormDescriptor", "d9/d42/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_form_descriptor.html", [
        [ "WpfHandler.UI.Controls.Logon.AdvancedRegistrationPanelDescriptor", "dd/d32/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_advanced_registration_panel_descriptor.html", null ],
        [ "WpfHandler.UI.Controls.Logon.DefaultRegistrationPanelDescriptor", "d4/daf/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_default_registration_panel_descriptor.html", null ]
      ] ]
    ] ],
    [ "UserControl", null, [
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.MainPluginControl", "d0/dbb/class_example_plugin1_1_1_main_plugin_control.html", null ],
      [ "ExamplePlugin1.PluginControl", "db/d3b/class_example_plugin1_1_1_plugin_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin1Control", "df/d40/class_example_plugin1_1_1_sub_plugin1_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin2Control", "d3/dc3/class_example_plugin1_1_1_sub_plugin2_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.SubPlugin3Control", "d3/d25/class_example_plugin1_1_1_sub_plugin3_control.html", null ],
      [ "ExamplePlugin1.UserControl1", "d3/d75/class_example_plugin1_1_1_user_control1.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.PluginControl", "d5/d91/class_example_plugin2_1_1_plugin_control.html", null ],
      [ "ExamplePlugin2.UserControl1", "de/dbb/class_example_plugin2_1_1_user_control1.html", null ],
      [ "SwitchPanelExample.HandlingPanel", "da/d43/class_switch_panel_example_1_1_handling_panel.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel1", "d2/d28/class_switch_panel_example_1_1_panel1.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "SwitchPanelExample.Panel2", "d3/dd3/class_switch_panel_example_1_1_panel2.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.AutoLayout.Controls.AutoLayoutVeiw", "d5/ddb/class_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_controls_1_1_auto_layout_veiw.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CatalogView", "dc/db6/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_view.html", null ],
      [ "WpfHandler.UI.Controls.CollectionControl", "d5/d8b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_collection_control.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatButton", "d0/d83/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.FlatTogglesGroup", "dd/dae/class_wpf_handler_1_1_u_i_1_1_controls_1_1_flat_toggles_group.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.Header", "d2/dc0/class_wpf_handler_1_1_u_i_1_1_controls_1_1_header.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.LockScreen", "dc/d68/class_wpf_handler_1_1_u_i_1_1_controls_1_1_lock_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonPanel", "d2/d77/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.LogonScreen", "d4/d25/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_logon_screen.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.Logon.RegistrationPanel", "d8/d0b/class_wpf_handler_1_1_u_i_1_1_controls_1_1_logon_1_1_registration_panel.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableFlatButton", "d3/d10/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_flat_button.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SelectableGrid", "de/dc7/class_wpf_handler_1_1_u_i_1_1_controls_1_1_selectable_grid.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.SwitchPanel", "de/d1c/class_wpf_handler_1_1_u_i_1_1_controls_1_1_switch_panel.html", null ],
      [ "WpfHandler.UI.Controls.TextFieldControl", "d2/dda/class_wpf_handler_1_1_u_i_1_1_controls_1_1_text_field_control.html", null ]
    ] ],
    [ "UserControl", null, [
      [ "WpfHandler.UI.Controls.CatalogButton", "d0/d24/class_wpf_handler_1_1_u_i_1_1_controls_1_1_catalog_button.html", null ]
    ] ],
    [ "WpfHandler.UI.AutoLayout.FormDescriptor.ValidationReport", "d7/d44/struct_wpf_handler_1_1_u_i_1_1_auto_layout_1_1_form_descriptor_1_1_validation_report.html", null ],
    [ "Window", null, [
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "AutoCollectionExample.MainWindow", "dc/dc5/class_auto_collection_example_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "ExamplePanelDescriptor.MainWindow", "db/daa/class_example_panel_descriptor_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "FlatButtonExample.MainWindow", "d6/d2d/class_flat_button_example_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LocalizationSample.MainWindow", "d6/d6f/class_localization_sample_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "LogonScreen.MainWindow", "dd/d66/class_logon_screen_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "MainPluginBasedApp.MainWindow", "d3/d87/class_main_plugin_based_app_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "SwitchPanelExample.MainWindow", "df/d1f/class_switch_panel_example_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TextFiledControls.MainWindow", "d9/ddd/class_text_filed_controls_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ],
      [ "TogglesGroupExample.MainWindow", "d6/d5a/class_toggles_group_example_1_1_main_window.html", null ]
    ] ]
];